server:
  port: 8091
  application:
    name: xfg-dev-tech-sso
  servlet:
    context-path: /auth
    session:
      cookie:
        name: OAuth2SSOToken

logging:
  level:
    root: debug
  config: classpath:logback-spring.xml